language: python

# http://docs.travis-ci.com/user/ci-environment/#CI-environment-OS
before_install:
  - travis_retry sudo ./bootstrap/ubuntu.sh
  - travis_retry sudo apt-get install --no-install-recommends nginx-light openssl

# using separate envs with different TOXENVs creates 4x1 Travis build
# matrix, which allows us to clearly distinguish which component under
# test has failed
env:
  global:
    - GOPATH=/tmp/go
  matrix:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=lint
    - TOXENV=cover

install: "travis_retry pip install tox coveralls"
before_script: '[ "${TOXENV:0:2}" != "py" ] || ./tests/boulder-start.sh'
# TODO: eliminate substring slice bashism
script: 'travis_retry tox && ([ "${TOXENV:0:2}" != "py" ] || (source .tox/$TOXENV/bin/activate && ./tests/boulder-integration.sh))'

after_success: '[ "$TOXENV" == "cover" ] && coveralls'

notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#letsencrypt"
    on_success: never
    on_failure: always
    use_notice: true
    skip_join: true
